version: "3"
services:
  gatling:
    build: ./gatling
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./gatling/results:/gatling/results:cached
      - ./gatling/simulations:/gatling/user-files/simulations
      - ./gatling/logback.xml:/gatling/conf/logback.xml
    environment:
      - baseUrl=http://localhost:8083
      - execUsers=1
      - execSeconds=1
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./gatling/results:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  mmock:
    image: jordimartin/mmock
    restart: always
    volumes:
      - ./mmock/config:/config
    ports:
      - "8082:8082"
      - "8083:8083"

